container\internal\raw_hash_set_test.cc(1288,10): warning C4477: 'printf' : format string '%ld' requires an argument of type 'long', but variadic argument 1 has type 'size_t' container\internal\raw_hash_set_test.cc(1336,16): error C2131: expression did not evaluate to a constant container\internal\raw_hash_set_test.cc(1349,44): error C3861: 'random': identifier not found